apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-feed
    version: v2
  name: backend-feed
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-feed
        version: v2
    spec:
      containers:
      - image: mirebole/udacity-c3-restapi-feed
        name: backend-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true       
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
