apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-user
    version: v2
  name: backend-user
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: backend-user
        version: v2
    spec:
      containers:
      - image: mirebole/udacity-c3-restapi-user
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL 
      restartPolicy: Always