version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mirebole/reverseproxy 
  backend_user:
    build:
      context: ../udacity-c3-restapi-user
    image: mirebole/udacity-c3-restapi-user
  backend_feed:
    build:
      context: ../udacity-c3-restapi-feed  
    image: mirebole/udacity-c3-restapi-feed
  frontend:
    build:
      context: ../udacity-c3-frontend  
    image: mirebole/udacity-c3-frontend:local