##build
FROM beevelop/ionic AS ionic
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN ionic build


##run
FROM nginx:alpine
COPY --from=ionic /usr/src/app/www /usr/share/nginx/html


